name: LuckyCache Redis Store CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install shards
        run: shards install
      - name: Format
        run: crystal tool format --check
      - name: Lint
        run: ./bin/ameba
      - name: Build shard entrypoint
        run: crystal build src/lucky_cache_redis_store.cr

  specs:
    strategy:
      fail-fast: false
      matrix:
        crystal_version: ["1.16.3", latest]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal_version }}
      - name: Install dependencies
        run: shards install --skip-postinstall --skip-executables
      - name: Run tests
        run: crystal spec
